stages:
  - build
  - test
  - bump
  - release

variables:
  BUILD_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG


build:
  stage: build
  tags:
    - rancher-runner
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - make push
    - tags


test:
  stage: test
  tags:
    - rancher-runner
  image: $BUILD_IMAGE
  variables:
    GIT_STRATEGY: none
  script:
    - make -C $XCMS_HOME test
  except:
    - tags


.bump: &bump-default
  stage: bump
  tags:
    - rancher-runner
  image: $BUILD_IMAGE
  variables:
    GIT_STRATEGY: clone
    BUMP: none
  script:
    - git config user.email || git config --global user.email "$GITLAB_USER_EMAIL"
    - git config user.name  || git config --global user.name  "Gitlab Build $CI_JOB_ID"
    - cd $CI_PROJECT_DIR
    - git checkout master
    - make bump/$BUMP
    - git remote set-url --push origin "git@git.ginkgobioworks.com:$CI_PROJECT_PATH.git"
    - git push --tags origin master
  when: manual
  only:
    - master
  except:
    - tags

bump-mod:
  <<: *bump-default
  variables:
    GIT_STRATEGY: clone
    BUMP: mod


release-package:
  stage: release
  environment:
    name: ginkgo-pypi
    url: https://pypi.ginkgobioworks.com/simple/xcms/
  tags:
    - rancher-runner
  variables:
    GIT_STRATEGY: none
  image: $BUILD_IMAGE
  script:
    - make -C $XCMS_HOME release
  only:
    - tags

release-image:
  stage: release
  variables:
    LATEST_IMAGE: $CI_REGISTRY_IMAGE:latest
  environment:
    name: docker-registry
    url: http://docker.ginkgobioworks.com/testpipe/xcms/
  tags:
    - rancher-runner
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $BUILD_IMAGE
    - docker tag $BUILD_IMAGE $LATEST_IMAGE
    - docker push $LATEST_IMAGE
  only:
    - tags

# Triggered from master, but releases from the github branch. This is because we don't want
# a .gitlab-ci.yml file in the github repo.
release-github:
  stage: release
  environment:
    name: github
    url: https://github.com/ginkgobioworks/xcms/
  tags:
    - rancher-runner
  image: $BUILD_IMAGE
  variables:
    GIT_STRATEGY: clone
  script:
    - cd $CI_PROJECT_DIR
    - git checkout github
    - git remote add github "git@github.com:ginkgobioworks/xcms.git"
    - git push --follow-tags github github:master
  when: manual
  only:
    - master
