#!/usr/bin/env bash

# multtest, msdata, and faahKO are needed for running unit tests
# Install xcms from bioconductor to automatically get all the deps; we'll install ourselves over
# that version

MAKEFLAGS='R_XTRA_CXXFLAGS=-Wno-deprecated-declarations' R --no-save <<EOR
  source("biocLite.R")
  biocLite(pkgs=c("xcms", "multtest", "msdata", "faahKO"), INSTALL_opts=c("--build"), ask=FALSE)
EOR

# Remove the BioConductor-installed XCMS, so it doesn't conflict with the one we build
rm -vf xcms*pc-linux-gnu.tar.gz
